<a href="https://colab.research.google.com/github/Freesoul-tech/AI-Data-Engineering/blob/main/dumy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
  # A=([[-1, 2,3],[4, -5, 6],[7,8,-9]])
  # B=([[0,2,1],[0,2,-8],[2,9,-1]])
  # C= A*B

  # C= [[6 ,29, -20], [8, 64, -44], [-18, 20, 102]]

import numpy as np

A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

C1 = np.matmul(A, B)
C2 = np.dot(A, B)

C3 = A @ B

print(C1)
print(C2)
print(C3)
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

c00 = a_ndarray[0, 0] * b_ndarray[0, 0] + a_ndarray[0, 1] * b_ndarray[1, 0] + a_ndarray[0, 2] * b_ndarray[2, 0]
print(c00)

def matrix_product(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

A = [[-1, 2, 3], [4, -5, 6], [7, 8, -9]]
B = [[0, 2, 1], [0, 2, -8], [2, 9, -1]]

C = matrix_product(A, B)
print(C)

def matrix_product_with_check(A, B):
    if len(A[0]) != len(B):
        print("Matrix multiplication is not defined for the given matrices.")
        return None
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

D = [[-1, 2, 3], [4, -5, 6]]
E = [[-9, 8, 7], [6, -5, 4]]

C = matrix_product_with_check(D, E)
print(C)
D_T = np.transpose(D)
C = matrix_product_with_check(D, D_T)
print(C)



[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
6
[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]
Matrix multiplication is not defined for the given matrices.
None
[[14, 4], [4, 77]]
